name: Feature Request
description: Suggest a new feature or improvement for NpcAPI
labels: [enhancement, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues to avoid duplicates.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature or improvement you're suggesting.
      placeholder: What would you like to see added or improved?
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Explain how this feature would be used and what problem it solves.
  - type: checkboxes
    id: server_software
    attributes:
      label: Server Software
      options:
        - label: Spigot
        - label: Paper
        - label: Other (please specify)
  - type: input
    id: server_version
    attributes:
      label: Server Version
      description: e.g., 1.21.11
      placeholder: 1.x.x
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
